In [25]:
import pandas as pd
import yaml
import sys
from pathlib import Path
import joblib
import numpy as np
from sklearn.model_selection import train_test_split
from typing import Tuple, Any
import warnings
warnings.filterwarnings('ignore')

# define project root
PROJECT_ROOT = Path().resolve().parent

# **Load Config**

In [26]:
def load_config(config_path: str) -> dict:
    """
    Load the configuration file.

    Parameters:
    -----------
    config_path (str): The path to the configuration file.

    Returns:
    --------
    config (dict): The loaded configuration as a dictionary.
    """
    try:
        with open(config_path, 'r') as file:
            config = yaml.safe_load(file)
        if config is None:
            raise ValueError("Configuration file is empty.")
        
    except FileNotFoundError:
        raise FileNotFoundError(f"Configuration file not found at: {config_path}")
    
    except yaml.YAMLError as e:
        raise ValueError(f"Error parsing YAML file: {e}")
    
    return config

# **Update Config**

In [27]:
def update_config(key: str, value: str, config_path: str) -> dict:
    """
    Update a specific key-value pair in the config file.
    
    Parameters:
    -----------
    key (str): The key to update in the config file.
    value (str): The new value to set for the specified key.
    config_path (str): The path to the configuration file.

    Returns:
    --------
    config (dict): The updated configuration as a dictionary.
    """

    # load config
    config = load_config(config_path)
    config[key] = value

    # open config file and write the updated config
    with open(config_path, 'w') as file:
        yaml.dump(config, file)
    
    print(f"Config updated: {key} set to {value}")

    # reload config
    return load_config(config_path)

In [28]:
# test the config load
config = load_config(config_path=PROJECT_ROOT / 'config' / 'config.yaml')
config

{'ALL_COLS': ['Age',
  'Attrition',
  'BusinessTravel',
  'DailyRate',
  'Department',
  'DistanceFromHome',
  'Education',
  'EducationField',
  'EnvironmentSatisfaction',
  'Gender',
  'HourlyRate',
  'JobInvolvement',
  'JobLevel',
  'JobRole',
  'JobSatisfaction',
  'MaritalStatus',
  'MonthlyIncome',
  'MonthlyRate',
  'NumCompaniesWorked',
  'OverTime',
  'PercentSalaryHike',
  'PerformanceRating',
  'RelationshipSatisfaction',
  'StockOptionLevel',
  'TotalWorkingYears',
  'TrainingTimesLastYear',
  'WorkLifeBalance',
  'YearsAtCompany',
  'YearsInCurrentRole',
  'YearsSinceLastPromotion',
  'YearsWithCurrManager'],
 'CAT_COLS': ['BusinessTravel',
  'Department',
  'EducationField',
  'Gender',
  'JobRole',
  'MaritalStatus',
  'OverTime'],
 'NUM_COLS': ['Age',
  'DailyRate',
  'DistanceFromHome',
  'Education',
  'EnvironmentSatisfaction',
  'HourlyRate',
  'JobInvolvement',
  'JobLevel',
  'JobSatisfaction',
  'MonthlyIncome',
  'MonthlyRate',
  'NumCompaniesWorked',
  'PercentSalaryHike',
  'PerformanceRating',
  'RelationshipSatisfaction',
  'StockOptionLevel',
  'TotalWorkingYears',
  'TrainingTimesLastYear',
  'WorkLifeBalance',
  'YearsAtCompany',
  'YearsInCurrentRole',
  'YearsSinceLastPromotion',
  'YearsWithCurrManager'],
 'N_CV': 5,
 'N_ITER': 40,
 'N_JOBS': -1,
 'PARAMS_CATBOOST': {'model__depth': [3, 5],
  'model__iterations': [100, 200, 300],
  'model__l2_leaf_reg': [3, 5, 7],
  'model__learning_rate': [0.01, 0.03, 0.05],
  'model__random_strength': [1, 3, 5]},
 'PARAMS_RFC': {'model__max_depth': [3, 5, 7],
  'model__max_features': ['sqrt', 'log2'],
  'model__min_samples_leaf': [2, 4, 6],
  'model__min_samples_split': [5, 10, 15],
  'model__n_estimators': [100, 150, 200]},
 'PARAMS_XGB': {'model__colsample_bytree': [0.7, 0.8],
  'model__learning_rate': [0.01, 0.03, 0.05],
  'model__max_depth': [3, 5],
  'model__min_child_weight': [3, 5, 7],
  'model__n_estimators': [100, 200, 300],
  'model__reg_alpha': [0, 0.5, 1],
  'model__reg_lambda': [1, 3, 5],
  'model__subsample': [0.7, 0.8]},
 'PATH_PROCESSED_DATA': 'attrition_processed.csv',
 'PATH_RAW_DATA': 'attrition_raw.csv',
 'PATH_TEST_DATA': ['X_test.pkl', 'y_test.pkl'],
 'PATH_TRAIN_DATA': ['X_train.pkl', 'y_train.pkl'],
 'RANDOM_STATE': 42,
 'RANGE_AGE': [18, 60],
 'RANGE_ATTRITION': [0, 1],
 'RANGE_DAILYRATE': [102, 1499],
 'RANGE_DISTANCEFROMHOME': [1, 29],
 'RANGE_EDUCATION': [1, 5],
 'RANGE_ENVIRONMENTSATISFACTION': [1, 4],
 'RANGE_HOURLYRATE': [30, 100],
 'RANGE_JOBINVOLVEMENT': [1, 4],
 'RANGE_JOBLEVEL': [1, 5],
 'RANGE_JOBSATISFACTION': [1, 4],
 'RANGE_MONTHLYINCOME': [1009, 19999],
 'RANGE_MONTHLYRATE': [2094, 26999],
 'RANGE_NUMCOMPANIESWORKED': [0, 9],
 'RANGE_PERCENTSALARYHIKE': [11, 25],
 'RANGE_PERFORMANCERATING': [3, 4],
 'RANGE_RELATIONSHIPSATISFACTION': [1, 4],
 'RANGE_STOCKOPTIONLEVEL': [0, 3],
 'RANGE_TOTALWORKINGYEARS': [0, 40],
 'RANGE_TRAININGTIMESLASTYEAR': [0, 6],
 'RANGE_WORKLIFEBALANCE': [1, 4],
 'RANGE_YEARSATCOMPANY': [0, 40],
 'RANGE_YEARSINCURRENTROLE': [0, 18],
 'RANGE_YEARSSINCELASTPROMOTION': [0, 15],
 'RANGE_YEARSWITHCURRMANAGER': [0, 17],
 'TARGET_COL': 'Attrition',
 'TEST_SIZE': 0.2}

# **About Dataset**

About Dataset

Uncover the factors that lead to employee attrition and explore important questions such as ‘show me a breakdown of distance from home by job role and attrition’ or ‘compare average monthly income by education and attrition’. This is a fictional data set created by IBM data scientists.

Education
- 1 = 'Below College'
- 2 = 'College'
- 3 = 'Bachelor'
- 4 = 'Master'
- 5 = 'Doctor'

EnvironmentSatisfaction
- 1 = 'Low'
- 2 = 'Medium'
- 3 = 'High'
- 4 = 'Very High'

JobInvolvement
- 1 = 'Low'
- 2 = 'Medium'
- 3 = 'High'
- 4 = 'Very High'

JobSatisfaction
- 1 = 'Low'
- 2 = 'Medium'
- 3 = 'High'
- 4 = 'Very High'

PerformanceRating
- 1 = 'Low'
- 2 = 'Good'
- 3 = 'Excellent'
- 4 = 'Outstanding'

RelationshipSatisfaction
- 1 = 'Low'
- 2 = 'Medium'
- 3 = 'High'
- 4 = 'Very High'

WorkLifeBalance
- 1 = 'Bad'
- 2 = 'Good'
- 3 = 'Better'
- 4 = 'Best'

# **Load Data**

In [29]:
def load_data(data_path: str) -> pd.DataFrame:
    """ 
    Load the raw data from the path specified in the config.

    Parameters:
    -----------
    data_path (str): The path to the raw data file.

    Returns:
    --------
    df (pd.DataFrame): The loaded raw data as a pandas DataFrame.
    """

    # make the validation layers 
    try:
        df = pd.read_csv(data_path)
        if df.empty:
            raise ValueError("The raw data file is empty. Please check the file content.")
        else:
            print(f"Raw data loaded successfully from: {data_path}")
            print(f"Data shape: {df.shape}")

    except Exception as e:
        raise ValueError(f"Error loading raw data: {e}")

    return df

In [30]:
data = load_data(data_path=PROJECT_ROOT / 'data' / 'raw' / config['PATH_RAW_DATA'])
data.head()

Raw data loaded successfully from: /home/bagaskoroah/employee_attrition/data/raw/attrition_raw.csv
Data shape: (1470, 35)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [31]:
# encode attrition to biner numbers
data['Attrition'] = data['Attrition'].replace({
    'No': 0,
    'Yes': 1
})

data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [32]:
# check duplicates
data.duplicated().sum()

np.int64(0)

# **Data Validation**

In [33]:
data.dtypes

Age                          int64
Attrition                    int64
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [34]:
# change education column to categorical
data['Education'] = data['Education'].astype('object')
data['Education'] = data['Education'].replace({
    1: 'Below College',
    2: 'College',
    3: 'Bachelor',
    4: 'Master',
    5: 'Doctor'
})

data.dtypes

Age                          int64
Attrition                    int64
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                   object
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [35]:
# sanity check on dataframe
data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,College,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,0,Travel_Frequently,279,Research & Development,8,Below College,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1,Travel_Rarely,1373,Research & Development,2,College,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,Master,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,0,Travel_Rarely,591,Research & Development,2,Below College,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [36]:
# drop irrelevant columns
data = data.drop(columns=['EmployeeCount', 'EmployeeNumber', 'Over18', 'StandardHours'])

# sanity check on dataframe
print('Data shape after dropping irrelevant columns:', data.shape)
data.head()

Data shape after dropping irrelevant columns: (1470, 31)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,College,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,0,Travel_Frequently,279,Research & Development,8,Below College,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,1,Travel_Rarely,1373,Research & Development,2,College,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,Master,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,0,Travel_Rarely,591,Research & Development,2,Below College,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2

In [37]:
for col in data.columns.tolist():
    print('Col:', col)
    print(data[col].value_counts(normalize=True))
    print('')

Col: Age
Age
35    0.053061
34    0.052381
36    0.046939
31    0.046939
29    0.046259
32    0.041497
30    0.040816
38    0.039456
33    0.039456
40    0.038776
37    0.034014
28    0.032653
27    0.032653
42    0.031293
39    0.028571
45    0.027891
41    0.027211
26    0.026531
44    0.022449
46    0.022449
43    0.021769
50    0.020408
25    0.017687
24    0.017687
49    0.016327
47    0.016327
55    0.014966
48    0.012925
51    0.012925
53    0.012925
54    0.012245
52    0.012245
22    0.010884
56    0.009524
58    0.009524
23    0.009524
21    0.008844
20    0.007483
59    0.006803
19    0.006122
18    0.005442
60    0.003401
57    0.002721
Name: proportion, dtype: float64

Col: Attrition
Attrition
0    0.838776
1    0.161224
Name: proportion, dtype: float64

Col: BusinessTravel
BusinessTravel
Travel_Rarely        0.709524
Travel_Frequently    0.188435
Non-Travel           0.102041
Name: proportion, dtype: float64

Col: DailyRate
DailyRate
691     0.004082
1082    0.003401
329     0.003401
530     0.003401
408     0.003401
          ...
1382    0.000680
161     0.000680
801     0.000680
642     0.000680
1154    0.000680
Name: proportion, Length: 886, dtype: float64

Col: Department
Department
Research & Development    0.653741
Sales                     0.303401
Human Resources           0.042857
Name: proportion, dtype: float64

Col: DistanceFromHome
DistanceFromHome
2     0.143537
1     0.141497
10    0.058503
9     0.057823
3     0.057143
7     0.057143
8     0.054422
5     0.044218
4     0.043537
6     0.040136
16    0.021769
11    0.019728
24    0.019048
29    0.018367
23    0.018367
15    0.017687
18    0.017687
20    0.017007
25    0.017007
26    0.017007
28    0.015646
19    0.014966
14    0.014286
12    0.013605
17    0.013605
22    0.012925
13    0.012925
21    0.012245
27    0.008163
Name: proportion, dtype: float64

Col: Education
Education
Bachelor         0.389116
Master           0.270748
College          0.191837
Below College    0.115646
Doctor           0.032653
Name: proportion, dtype: float64

Col: EducationField
EducationField
Life Sciences       0.412245
Medical             0.315646
Marketing           0.108163
Technical Degree    0.089796
Other               0.055782
Human Resources     0.018367
Name: proportion, dtype: float64

Col: EnvironmentSatisfaction
EnvironmentSatisfaction
3    0.308163
4    0.303401
2    0.195238
1    0.193197
Name: proportion, dtype: float64

Col: Gender
Gender
Male      0.6
Female    0.4
Name: proportion, dtype: float64

Col: HourlyRate
HourlyRate
66    0.019728
84    0.019048
42    0.019048
98    0.019048
48    0.019048
        ...
89    0.010204
53    0.009524
68    0.009524
38    0.008844
34    0.008163
Name: proportion, Length: 71, dtype: float64

Col: JobInvolvement
JobInvolvement
3    0.590476
2    0.255102
4    0.097959
1    0.056463
Name: proportion, dtype: float64

Col: JobLevel
JobLevel
1    0.369388
2    0.363265
3    0.148299
4    0.072109
5    0.046939
Name: proportion, dtype: float64

Col: JobRole
JobRole
Sales Executive              0.221769
Research Scientist           0.198639
Laboratory Technician        0.176190
Manufacturing Director       0.098639
Healthcare Representative    0.089116
Manager                      0.069388
Sales Representative         0.056463
Research Director            0.054422
Human Resources              0.035374
Name: proportion, dtype: float64

Col: JobSatisfaction
JobSatisfaction
4    0.312245
3    0.300680
1    0.196599
2    0.190476
Name: proportion, dtype: float64

Col: MaritalStatus
MaritalStatus
Married     0.457823
Single      0.319728
Divorced    0.222449
Name: proportion, dtype: float64

Col: MonthlyIncome
MonthlyIncome
2342     0.002721
3452     0.002041
2559     0.002041
2610     0.002041
2451     0.002041
           ...
3041     0.000680
2579     0.000680
5985     0.000680
15402    0.000680
2083     0.000680
Name: proportion, Length: 1349, dtype: float64

Col: MonthlyRate
MonthlyRate
4223     0.002041
9150     0.002041
21534    0.001361
22074    0.001361
25326    0.001361
           ...
3010     0.000680
5013     0.000680
6219     0.000680
14004    0.000680
26894    0.000680
Name: proportion, Length: 1427, dtype: float64

Col: NumCompaniesWorked
NumCompaniesWorked
1    0.354422
0    0.134014
3    0.108163
2    0.099320
4    0.094558
7    0.050340
6    0.047619
5    0.042857
9    0.035374
8    0.033333
Name: proportion, dtype: float64

Col: OverTime
OverTime
No     0.717007
Yes    0.282993
Name: proportion, dtype: float64

Col: PercentSalaryHike
PercentSalaryHike
11    0.142857
13    0.142177
14    0.136735
12    0.134694
15    0.068707
18    0.060544
17    0.055782
16    0.053061
19    0.051701
22    0.038095
20    0.037415
21    0.032653
23    0.019048
24    0.014286
25    0.012245
Name: proportion, dtype: float64

Col: PerformanceRating
PerformanceRating
3    0.846259
4    0.153741
Name: proportion, dtype: float64

Col: RelationshipSatisfaction
RelationshipSatisfaction
3    0.312245
4    0.293878
2    0.206122
1    0.187755
Name: proportion, dtype: float64

Col: StockOptionLevel
StockOptionLevel
0    0.429252
1    0.405442
2    0.107483
3    0.057823
Name: proportion, dtype: float64

Col: TotalWorkingYears
TotalWorkingYears
10    0.137415
6     0.085034
8     0.070068
9     0.065306
5     0.059864
7     0.055102
1     0.055102
4     0.042857
12    0.032653
3     0.028571
15    0.027211
16    0.025170
11    0.024490
13    0.024490
21    0.023129
17    0.022449
14    0.021088
2     0.021088
20    0.020408
18    0.018367
19    0.014966
23    0.014966
22    0.014286
24    0.012245
26    0.009524
25    0.009524
28    0.009524
0     0.007483
29    0.006803
31    0.006122
32    0.006122
30    0.004762
33    0.004762
27    0.004762
36    0.004082
34    0.003401
37    0.002721
35    0.002041
40    0.001361
38    0.000680
Name: proportion, dtype: float64

Col: TrainingTimesLastYear
TrainingTimesLastYear
2    0.372109
3    0.334014
4    0.083673
5    0.080952
1    0.048299
6    0.044218
0    0.036735
Name: proportion, dtype: float64

Col: WorkLifeBalance
WorkLifeBalance
3    0.607483
2    0.234014
4    0.104082
1    0.054422
Name: proportion, dtype: float64

Col: YearsAtCompany
YearsAtCompany
5     0.133333
1     0.116327
3     0.087075
2     0.086395
10    0.081633
4     0.074830
7     0.061224
9     0.055782
8     0.054422
6     0.051701
0     0.029932
11    0.021769
20    0.018367
13    0.016327
15    0.013605
14    0.012245
22    0.010204
21    0.009524
12    0.009524
18    0.008844
16    0.008163
19    0.007483
17    0.006122
24    0.004082
33    0.003401
26    0.002721
25    0.002721
31    0.002041
32    0.002041
27    0.001361
29    0.001361
36    0.001361
23    0.001361
37    0.000680
40    0.000680
34    0.000680
30    0.000680
Name: proportion, dtype: float64

Col: YearsInCurrentRole
YearsInCurrentRole
2     0.253061
0     0.165986
7     0.151020
3     0.091837
4     0.070748
8     0.060544
9     0.045578
1     0.038776
6     0.025170
5     0.024490
10    0.019728
11    0.014966
13    0.009524
14    0.007483
12    0.006803
15    0.005442
16    0.004762
17    0.002721
18    0.001361
Name: proportion, dtype: float64

Col: YearsSinceLastPromotion
YearsSinceLastPromotion
0     0.395238
1     0.242857
2     0.108163
7     0.051701
4     0.041497
3     0.035374
5     0.030612
6     0.021769
11    0.016327
8     0.012245
9     0.011565
15    0.008844
13    0.006803
12    0.006803
14    0.006122
10    0.004082
Name: proportion, dtype: float64

Col: YearsWithCurrManager
YearsWithCurrManager
2     0.234014
0     0.178912
7     0.146939
3     0.096599
8     0.072789
4     0.066667
1     0.051701
9     0.043537
5     0.021088
6     0.019728
10    0.018367
11    0.014966
12    0.012245
13    0.009524
17    0.004762
15    0.003401
14    0.003401
16    0.001361
Name: proportion, dtype: float64

In [38]:
# separate each column by data type
num_cols = data.select_dtypes(include=['int64', 'float64']).columns
obj_cols = set(data.columns).difference(set(num_cols))

config = update_config(key='ALL_COLS', value=data.columns.tolist(), config_path=PROJECT_ROOT / 'config' / 'config.yaml')
config = update_config(key='TARGET_COL', value='Attrition', config_path=PROJECT_ROOT / 'config' / 'config.yaml')

Config updated: ALL_COLS set to ['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome', 'Education', 'EducationField', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']
Config updated: TARGET_COL set to Attrition

In [39]:
# update range of each numeric columns
keys = [f'RANGE_{col.upper()}' for col in num_cols]

for col, key in zip(num_cols, keys):
    config = update_config(
        key=key,
        value=[int(np.min(data[col])), int(np.max(data[col]))],
        config_path=PROJECT_ROOT / 'config' / 'config.yaml'
    )

Config updated: RANGE_AGE set to [18, 60]
Config updated: RANGE_ATTRITION set to [0, 1]
Config updated: RANGE_DAILYRATE set to [102, 1499]

Config updated: RANGE_DISTANCEFROMHOME set to [1, 29]
Config updated: RANGE_ENVIRONMENTSATISFACTION set to [1, 4]
Config updated: RANGE_HOURLYRATE set to [30, 100]
Config updated: RANGE_JOBINVOLVEMENT set to [1, 4]
Config updated: RANGE_JOBLEVEL set to [1, 5]
Config updated: RANGE_JOBSATISFACTION set to [1, 4]
Config updated: RANGE_MONTHLYINCOME set to [1009, 19999]
Config updated: RANGE_MONTHLYRATE set to [2094, 26999]
Config updated: RANGE_NUMCOMPANIESWORKED set to [0, 9]
Config updated: RANGE_PERCENTSALARYHIKE set to [11, 25]
Config updated: RANGE_PERFORMANCERATING set to [3, 4]
Config updated: RANGE_RELATIONSHIPSATISFACTION set to [1, 4]
Config updated: RANGE_STOCKOPTIONLEVEL set to [0, 3]
Config updated: RANGE_TOTALWORKINGYEARS set to [0, 40]
Config updated: RANGE_TRAININGTIMESLASTYEAR set to [0, 6]
Config updated: RANGE_WORKLIFEBALANCE set to [1, 4]
Config updated: RANGE_YEARSATCOMPANY set to [0, 40]
Config updated: RANGE_YEARSINCURRENTROLE set to [0, 18]
Config updated: RANGE_YEARSSINCELASTPROMOTION set to [0, 15]
Config updated: RANGE_YEARSWITHCURRMANAGER set to [0, 17]

# **Data Defense**

In [40]:
def check_data(data: pd.DataFrame, config: dict) -> None:
    """
    Check the data against the specifications in the config file.

    Parameters:
    -----------
    data (pd.DataFrame): The data to be checked.
    config (dict): The configuration file.

    Returns:
    --------
    None: The function will raise an assertion error if any of the checks fail.
    """
    # check data types
    assert set(data.columns) == set(config['ALL_COLS']), "Data columns don't match the all columns specified in the config file."
    assert set(data.select_dtypes(include=['object']).columns) == set(obj_cols), "Object columns don't match."
    assert set(data.select_dtypes(include=['int64', 'float64']).columns) == set(num_cols), "Numerical columns don't match."

    # check target column
    assert config['TARGET_COL'] in data.columns, "Target column specified in the config file is not present in the data."
    
    # check range of numeric columns
    for col in num_cols:
        assert data[col].between(config[f'RANGE_{col.upper()}'][0], config[f'RANGE_{col.upper()}'][1]).sum() == len(data), f"An error occurred in {col} range. Please check the data and config file."

In [41]:
# execute check data function
check_data(data=data, config=config)

# **Data Split**

In [42]:
def split_data(data: pd.DataFrame, config: dict) -> Tuple[pd.DataFrame, pd.DataFrame, pd.Series, pd.Series]:

    """

    Split the data into training and testing sets.

    Parameters:
    -----------
    data (pd.DataFrame): The data to be split.
    config (dict): The configuration file.

    Returns:
    --------
    X_train (pd.DataFrame): The training input features.
    X_test (pd.DataFrame): The testing input features.
    y_train (pd.Series): The training target variable.
    y_test (pd.Series): The testing target variable.

    """

    # split input and output
    X = data.drop(columns=[config['TARGET_COL']])
    y = data[config['TARGET_COL']]

    # split train and test
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=config['TEST_SIZE'], random_state=config['RANDOM_STATE'], stratify=y
    )
    
    print(f'Data split into training and testing sets successfully.')
    print(f'X_train shape: {X_train.shape}, y_train shape: {y_train.shape}')
    print(f'X_test shape: {X_test.shape}, y_test shape: {y_test.shape}')

    return X_train, X_test, y_train, y_test

In [43]:
X_train, X_test, y_train, y_test = split_data(data=data, config=config)

Data split into training and testing sets successfully.
X_train shape: (1176, 30), y_train shape: (1176,)
X_test shape: (294, 30), y_test shape: (294,)

In [44]:
# split cat and num cols
cat_cols_train = X_train.select_dtypes(include='object').columns.tolist()
num_cols_train = X_train.select_dtypes(include=['int64', 'float64']).columns.tolist()

config = update_config(key='CAT_COLS', value=cat_cols_train, config_path=PROJECT_ROOT / 'config' / 'config.yaml')
config = update_config(key='NUM_COLS', value=num_cols_train, config_path=PROJECT_ROOT / 'config' / 'config.yaml')

Config updated: CAT_COLS set to ['BusinessTravel', 'Department', 'Education', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']
Config updated: NUM_COLS set to ['Age', 'DailyRate', 'DistanceFromHome', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

In [45]:
# define a function to serialize any object
def serialize_object(path: str, obj: Any) -> None:
    """ 
    Serialize the object into specified path.

    Parameters:
    -----------
    path (str): The path to save the serialized object.
    obj (Any): The object to be serialized.

    Returns:
    --------
    None
    """
    # save the object to the specified path
    joblib.dump(value=obj, filename=path)
    print(f'Saving object. . . .')
    print(f'Object serialized successfully to: {path}')

In [46]:
# serialize the splitted data
path_splitted_data = PROJECT_ROOT / 'data' / 'interim' 
serialize_object(path=path_splitted_data / 'X_train.pkl', obj=X_train)
serialize_object(path=path_splitted_data / 'X_test.pkl', obj=X_test)
serialize_object(path=path_splitted_data / 'y_train.pkl', obj=y_train)
serialize_object(path=path_splitted_data / 'y_test.pkl', obj=y_test)

Saving object. . . .
Object serialized successfully to: /home/bagaskoroah/employee_attrition/data/interim/X_train.pkl
Saving object. . . .
Object serialized successfully to: /home/bagaskoroah/employee_attrition/data/interim/X_test.pkl
Saving object. . . .
Object serialized successfully to: /home/bagaskoroah/employee_attrition/data/interim/y_train.pkl
Saving object. . . .
Object serialized successfully to: /home/bagaskoroah/employee_attrition/data/interim/y_test.pkl

# **Update Config**

In [47]:
# update splitted data path to config
config = update_config(
    key='PATH_TRAIN_DATA',
    value=['X_train.pkl', 'y_train.pkl'],
    config_path=PROJECT_ROOT / 'config' / 'config.yaml'
)

config = update_config(
    key='PATH_TEST_DATA',
    value=[f'X_test.pkl', 'y_test.pkl'],
    config_path=PROJECT_ROOT / 'config' / 'config.yaml'
)

Config updated: PATH_TRAIN_DATA set to ['X_train.pkl', 'y_train.pkl']
Config updated: PATH_TEST_DATA set to ['X_test.pkl', 'y_test.pkl']

In [48]:
# sanity check on config yaml file
config

{'ALL_COLS': ['Age',
  'Attrition',
  'BusinessTravel',
  'DailyRate',
  'Department',
  'DistanceFromHome',
  'Education',
  'EducationField',
  'EnvironmentSatisfaction',
  'Gender',
  'HourlyRate',
  'JobInvolvement',
  'JobLevel',
  'JobRole',
  'JobSatisfaction',
  'MaritalStatus',
  'MonthlyIncome',
  'MonthlyRate',
  'NumCompaniesWorked',
  'OverTime',
  'PercentSalaryHike',
  'PerformanceRating',
  'RelationshipSatisfaction',
  'StockOptionLevel',
  'TotalWorkingYears',
  'TrainingTimesLastYear',
  'WorkLifeBalance',
  'YearsAtCompany',
  'YearsInCurrentRole',
  'YearsSinceLastPromotion',
  'YearsWithCurrManager'],
 'CAT_COLS': ['BusinessTravel',
  'Department',
  'Education',
  'EducationField',
  'Gender',
  'JobRole',
  'MaritalStatus',
  'OverTime'],
 'NUM_COLS': ['Age',
  'DailyRate',
  'DistanceFromHome',
  'EnvironmentSatisfaction',
  'HourlyRate',
  'JobInvolvement',
  'JobLevel',
  'JobSatisfaction',
  'MonthlyIncome',
  'MonthlyRate',
  'NumCompaniesWorked',
  'PercentSalaryHike',
  'PerformanceRating',
  'RelationshipSatisfaction',
  'StockOptionLevel',
  'TotalWorkingYears',
  'TrainingTimesLastYear',
  'WorkLifeBalance',
  'YearsAtCompany',
  'YearsInCurrentRole',
  'YearsSinceLastPromotion',
  'YearsWithCurrManager'],
 'N_CV': 5,
 'N_ITER': 40,
 'N_JOBS': -1,
 'PARAMS_CATBOOST': {'model__depth': [3, 5],
  'model__iterations': [100, 200, 300],
  'model__l2_leaf_reg': [3, 5, 7],
  'model__learning_rate': [0.01, 0.03, 0.05],
  'model__random_strength': [1, 3, 5]},
 'PARAMS_RFC': {'model__max_depth': [3, 5, 7],
  'model__max_features': ['sqrt', 'log2'],
  'model__min_samples_leaf': [2, 4, 6],
  'model__min_samples_split': [5, 10, 15],
  'model__n_estimators': [100, 150, 200]},
 'PARAMS_XGB': {'model__colsample_bytree': [0.7, 0.8],
  'model__learning_rate': [0.01, 0.03, 0.05],
  'model__max_depth': [3, 5],
  'model__min_child_weight': [3, 5, 7],
  'model__n_estimators': [100, 200, 300],
  'model__reg_alpha': [0, 0.5, 1],
  'model__reg_lambda': [1, 3, 5],
  'model__subsample': [0.7, 0.8]},
 'PATH_PROCESSED_DATA': 'attrition_processed.csv',
 'PATH_RAW_DATA': 'attrition_raw.csv',
 'PATH_TEST_DATA': ['X_test.pkl', 'y_test.pkl'],
 'PATH_TRAIN_DATA': ['X_train.pkl', 'y_train.pkl'],
 'RANDOM_STATE': 42,
 'RANGE_AGE': [18, 60],
 'RANGE_ATTRITION': [0, 1],
 'RANGE_DAILYRATE': [102, 1499],
 'RANGE_DISTANCEFROMHOME': [1, 29],
 'RANGE_EDUCATION': [1, 5],
 'RANGE_ENVIRONMENTSATISFACTION': [1, 4],
 'RANGE_HOURLYRATE': [30, 100],
 'RANGE_JOBINVOLVEMENT': [1, 4],
 'RANGE_JOBLEVEL': [1, 5],
 'RANGE_JOBSATISFACTION': [1, 4],
 'RANGE_MONTHLYINCOME': [1009, 19999],
 'RANGE_MONTHLYRATE': [2094, 26999],
 'RANGE_NUMCOMPANIESWORKED': [0, 9],
 'RANGE_PERCENTSALARYHIKE': [11, 25],
 'RANGE_PERFORMANCERATING': [3, 4],
 'RANGE_RELATIONSHIPSATISFACTION': [1, 4],
 'RANGE_STOCKOPTIONLEVEL': [0, 3],
 'RANGE_TOTALWORKINGYEARS': [0, 40],
 'RANGE_TRAININGTIMESLASTYEAR': [0, 6],
 'RANGE_WORKLIFEBALANCE': [1, 4],
 'RANGE_YEARSATCOMPANY': [0, 40],
 'RANGE_YEARSINCURRENTROLE': [0, 18],
 'RANGE_YEARSSINCELASTPROMOTION': [0, 15],
 'RANGE_YEARSWITHCURRMANAGER': [0, 17],
 'TARGET_COL': 'Attrition',
 'TEST_SIZE': 0.2}